### ISSUE TITLE
Publish to open-vsx.org as VSCode users cannot use the Microsoft Marketplace legally

### ISSUE THREAD

**Issue by creeloper27** [Lemmmy/computercraft-extension-pack#1]
~~**NOTE: This is currently not possible as the [ComputerCraft API autocomplete extension](https://marketplace.visualstudio.com/items?itemName=jackmacwindows.vscode-computercraft) by [JackMacWindows](https://marketplace.visualstudio.com/publishers/jackmacwindows) is not currently on the [Open VSX Registry](https://open-vsx.org/), tho I have opened an Issue regarding that just now, hopefully he will publish it there as well so that this becomes possible as well. 🤞**~~
edit: ComputerCraft API autocomplete extension has now been added to open-vsx as well! [owner comment](https://github.com/MCJack123/vscode-computercraft/issues/8#issuecomment-1734633331), [open-vsx page](https://open-vsx.org/extension/JackMacWindows/vscode-computercraft).

It would be super nice if you could also publish this extension on the [Open VSX Registry](https://open-vsx.org/) as people using [VSCodium](https://vscodium.com/) (Free/Libre Open Source Software Binaries of VS Code) [cannot legally use the Microsoft Marketplace](https://github.com/microsoft/vscode/issues/31168) so me and other users that use [VSCodium](https://vscodium.com/) need to manually go on the [Microsoft Marketplace Website](https://marketplace.visualstudio.com/vscode), find the estension there ([here](https://marketplace.visualstudio.com/items?itemName=jackmacwindows.vscode-computercraft)), click `Download Extension` then install the downloaded .vsix file like shown [here](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) which is quite an annoying and user unfriendly process.
To publish extensions on the [Open VSX Registry](https://open-vsx.org/) there is [this guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thanks in advance and Especially Thanks for Making this Awesome Extension! :D

**Comment by creeloper27** [comment]
I have updated this Issue as this is now possible.

**Comment by Lemmmy** [comment]
Thanks for the guide. That was an incredibly convoluted and unfriendly process! Hopefully all done: https://open-vsx.org/extension/lemmmy/computercraft-extension-pack

**Comment by creeloper27** [comment]
Thanks a lot for publishing to [open-vsx](https://open-vsx.org/)! :D

Just one last thing, I suggest updating the links in the [open-vsx](https://open-vsx.org/) version of your extension ([computercraft-extension-pack](https://open-vsx.org/extension/lemmmy/computercraft-extension-pack)) to point to the extensions and profiles on [open-vsx](https://open-vsx.org/) instead of the [Microsoft Marketplace].(https://marketplace.visualstudio.com/vscode)

I am referring to these:
![image](https://github.com/Lemmmy/computercraft-extension-pack/assets/20074177/e8494cd0-373a-4ccf-b219-738c2973f616)

These are the respective [open-vsx](https://open-vsx.org/) links:
[ComputerCraft API autocomplete extension](https://open-vsx.org/extension/JackMacWindows/vscode-computercraft)
[JackMacWindows](https://open-vsx.org/namespace/JackMacWindows)
[Lua Language Server](https://open-vsx.org/extension/sumneko/lua)
[sumneko](https://open-vsx.org/namespace/sumneko)

Regarding [Share Code](https://marketplace.visualstudio.com/items?itemName=RolandGreim.sharecode) by [RolandGreim](https://marketplace.visualstudio.com/publishers/RolandGreim) I have [opened an Issue there](https://github.com/tigerxy/VSCode-ShareCode/issues/33) and will try to make a new Issue in this repository it he publishes his extension on [open-vsx](https://open-vsx.org/) as well.
