### ISSUE TITLE
README Instructions Unclear

### ISSUE THREAD

**Issue by creeloper27** [Lemmmy/computercraft-extension-pack#2]
The [README](https://github.com/Lemmmy/computercraft-extension-pack/blob/master/README.md) currently says:

> The following configuration is recommended (<kbd>F1</kbd> → `Preferences: Open Settings (JSON)`):

Tho if I type in the `Command Palette` `Preferences: Open Settings (JSON)` I get:
`Preferences: Open Default Settings (JSON)`
and
`Preferences: Open User Settings (JSON)`

![Screenshot_20230908_193655](https://github.com/Lemmmy/computercraft-extension-pack/assets/20074177/59d3df5d-a027-4c87-be81-7a53784857b1)

I suppose It's probably fine putting those configurations in either tho I'm unsure.

**Comment by Lemmmy** [comment]
This is a change VSCode made since the README was written - "Default Settings" is read-only, "User Settings" is what you're looking for. Feel free to submit a PR.
